image: node:14.15.0-stretch
stages:
  - build
  - test

install_dependencies:
  stage: build
  script: yarn install
  artifacts:
    paths:        
      - node_modules  
#yarn.log  key cacsh artifacts
  cache:
    key:
      files:
        - yan.lock        
    paths:
      - node_modules
# .eslintrc.js plugin "error" linter off         
run_tests:
  stage: test
  script: CI=true yarn test
run_linter:
  stage: test
  script: yarn run eslint src/**.js  
